services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secretaryship'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
